module.exports = [
    {
		title:'Contents',
		index: '0',
		type:'toPuzzles',
        link: 'puzzles contents',
        data:{

            },

    },
    {
		title:'Today\'s Puzzle',
		index: '1',
		type:'toPuzzles',
        link: 'game board',
        data:{

            },

    },
    {
		title:'Daily Puzzles',
		index: '2',
		type:'toPuzzles',
        link: 'daily launcher',
        data:{

            },

    },
    {
		title:'Easy',
		index: '3',
		type:'store',
        link: 'store',
        data:[
                    {
                    name: 'Capri',
                    product_id: 'fragmental.e.capri50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#00BFFF',
                    },
                    {
                    name: 'Chartreuse',
                    product_id: 'fragmental.e.chartreuse50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#DFFF00',
                    },
                    {
                    name: 'Electric Indigo',
                    product_id: 'fragmental.e.electric_indigo50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#6F00FF',
                    },
                    {
                    name: 'Ferrari Red',
                    product_id: 'fragmental.e.ferrari_red50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#FF2800',
                    },
                    {
                    name: 'Guppie Green',
                    product_id: 'fragmental.e.guppie_green50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#00FF7F',
                    },
                    {
                    name: 'Lavender Blue',
                    product_id: 'fragmental.e.lavender_blue50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'E',
                    color: '#CCCCFF',
                    },
                    {
                    name: 'Mango Tango',
                    product_id: 'fragmental.e.mango_tango100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'E',
                    color: '#FF8243',
                    },
                    {
                    name: 'Hot Phlox',
                    product_id: 'fragmental.e.hot_phlox100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'E',
                    color: '#DF00FF',
                    },
                    {
                    name: 'Tasty Turquoise',
                    product_id: 'fragmental.e.tasty_turquoise100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'E',
                    color: '#00FFEF',
                    },
                    {
                    name: 'Wild Strawberry',
                    product_id: 'fragmental.e.wild_strawberry100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'E',
                    color: '#FF43A4',
                    },
            ],
    },
    {
		title:'Moderate',
		index: '4',
		type:'store',
        link: 'store',
        data:[
                    {
                    name: 'Bungalow',
                    product_id: 'fragmental.m.bungalow50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#138808',
                    },
                    {
                    name: 'Cruise',
                    product_id: 'fragmental.m.cruise50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#2A52BE',
                    },
                    {
                    name: 'Getaway',
                    product_id: 'fragmental.m.getaway50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#800000',
                    },
                    {
                    name: 'Holiday',
                    product_id: 'fragmental.m.holiday50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#FEFE22',
                    },
                    {
                    name: 'Road Trip',
                    product_id: 'fragmental.m.road_trip50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#98817B',
                    },
                    {
                    name: 'Siesta',
                    product_id: 'fragmental.m.siesta50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'M',
                    color: '#082567',
                    },
                    {
                    name: 'Tropics',
                    product_id: 'fragmental.m.tropics100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'M',
                    color: '#C71585',
                    },
                    {
                    name: 'Vacation',
                    product_id: 'fragmental.m.vacation100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'M',
                    color: '#CBA135',
                    },
                    {
                    name: 'Villa',
                    product_id: 'fragmental.m.villa100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'M',
                    color: '#FFC40C',
                    },
                    {
                    name: 'Weekender',
                    product_id: 'fragmental.m.weekender100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'M',
                    color: '#195905',
                    },
            ],
    },
    {
		title:'Hard',
		index: '5',
		type:'store',
        link: 'store',
        data:[
                    {
                    name: 'Blizzard',
                    product_id: 'fragmental.h.blizzard50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#E7FEFF',
                    },
                    {
                    name: 'Cyclone',
                    product_id: 'fragmental.h.cyclone50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#DE3163',
                    },
                    {
                    name: 'Dust',
                    product_id: 'fragmental.h.dust50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#FFCBA4',
                    },
                    {
                    name: 'Electrical',
                    product_id: 'fragmental.h.electrical50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#7DF9FF',
                    },
                    {
                    name: 'Hurricane',
                    product_id: 'fragmental.h.hurricane50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#8F00FF',
                    },
                    {
                    name: 'Southwester',
                    product_id: 'fragmental.h.southwester50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#FFCC33',
                    },
                    {
                    name: 'Squall',
                    product_id: 'fragmental.h.squall100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'H',
                    color: '#A52A2A',
                    },
                    {
                    name: 'Tempest',
                    product_id: 'fragmental.h.tempest100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'H',
                    color: '#007BA7',
                    },
                    {
                    name: 'Thunderstorm',
                    product_id: 'fragmental.h.thunderstorm100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'H',
                    color: '#3B444B',
                    },
                    {
                    name: 'Typhoon',
                    product_id: 'fragmental.h.typhoon100',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: '100',
                    difficulty: 'H',
                    color: '#5D8AA8',
                    },
            ],
    },
    {
		title:'Theme',
		index: '6',
		type:'store',
        link: 'store',
        data:[
                    {
                    name: 'Art',
                    product_id: 'fragmental.t.art50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#A50B5E',
                    },
                    {
                    name: 'Business',
                    product_id: 'fragmental.t.business50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#087830',
                    },
                    {
                    name: 'Entertainment',
                    product_id: 'fragmental.t.entertainment50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#9457EB',
                    },
                    {
                    name: 'Explorers',
                    product_id: 'fragmental.t.explorers50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#29AB87',
                    },
                    {
                    name: 'Food and Drink',
                    product_id: 'fragmental.t.food_and_drink50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#AAF0D1',
                    },
                    {
                    name: 'Geography',
                    product_id: 'fragmental.t.geography50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#FADA5E',
                    },
                    {
                    name: 'History',
                    product_id: 'fragmental.t.history50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#796878',
                    },
                    {
                    name: 'Music',
                    product_id: 'fragmental.t.music50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#B784A7',
                    },
                    {
                    name: 'Quotations',
                    product_id: 'fragmental.t.quotations50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#FDF5E6',
                    },
                    {
                    name: 'Science',
                    product_id: 'fragmental.t.science50',
                    price: '$1.99',
                    show: 'true',
                    num_puzzles: '50',
                    difficulty: 'H',
                    color: '#FF4500',
                    },
            ],

    },
    {
		title:'Easy Combos',
		index: '7',
		type:'combos',
        link: 'store3',
        data:[
                    {
                    name: ['Capri', 'Chartreuse', 'Electric Indigo'],
                    product_id: 'fragmental.ec.capri150',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: ['50','50','50'],
                    difficulty: ['E','E','E'],
                    color: ['#00BFFF','#DFFF00','#6F00FF']
                    },
                    {
                    name: ['Ferrari Red','Guppie Green','Lavender Blue'],
                    product_id: 'fragmental.e.ferrari_red50',
                    price: '$2.99',
                    show: 'true',
                    num_puzzles: ['50','50','50'],
                    difficulty: ['E','E','E'],
                    color: ['#FF2800','#00FF7F','#CCCCFF']
                    },
                    {
                    name: ['Mango Tango','Hot Phlox','Tasty Turquoise'],
                    product_id: 'fragmental.e.mango_tango100',
                    price: '$3.99',
                    show: 'true',
                    num_puzzles: ['100','100','100'],
                    difficulty: ['E','E','E'],
                    color: ['#FF8243','#DF00FF','#00FFEF']
                    },
            ],
    },
    {
		title:'Moderate Combos',
		index: '8',
		type:'combos',
        link: 'store3',
        data:{

            },

    },
    {
		title:'Hard Combos',
		index: '9',
		type:'combos',
        link: 'store3',
        data:{

            },

    },
    {
		title:'Mixed Combos',
		index: '10',
		type:'combos',
        link: 'store3',
        data:{

            },

    },
    {
		title:'Facebook',
		index: '11',
		type:'social',
        link: '',
        data:{

            },

    },
    {
		title:'Twitter',
		index: '12',
		type:'social',
        link: '',
        data:{

            },

    },
    {
		title:'How To Play',
		index: '13',
		type:'about',
        link: 'app_intro',
        data:{

            },

    },
    {
		title:'Settings',
		index: '14',
		type:'about',
        link: '',
        data:{

            },

    },
    {
		title:'About',
		index: '15',
		type:'about',
        link: '',
        data:{

            },

    },

	{
		title:'Today\'s Puzzle',
		index: '16',
		type:'daily',
		show:'true',
		num_puzzles:'1',
		num_solved:'0',
		solved:'false',
		bg_color:'#079707',
		puzzles:[
			're~^|ce|des:Moves back, as a hairline**ent|^|es:They\'re sometimes served on trays**^|si|gns:Bows out**ig|no|^:Look the other way**^|exa|mi|ne:Take another good look at**sh|oes|to|^:Establishment with many horns**fo|^|st|er:Tree manager**fo|^|ign|er:Lou Graham-led arena rock band'
			],
	},
	{
		title:'Last Three Days',
		index: '17',
		type:'daily',
		show:'true',
		num_puzzles:'3',
		num_solved:'0',
		solved:'false',
		bg_color:'#C0C0C0',
		puzzles:[
            'le~^|ger|de|ma|in:Sleight of hand**^|ek:Drip of the onion family?**^|er|ed:Looked at with smarmy intent**^|wd:R-rated, maybe**cl|ue|^|ss:1995 Alicia Silverstone flick**si|nk|ho|^:Bigger than your run-of-the-mill pothole**^|is:Hawaiian garlands**^|thar|gy:Sluggishness**in|evi|tab|^:Fated',
            'res~expo|su|^:Photos, pre-digital**^|id|ue:Last vestige**lu|^:At the end of the line**^|tu|dy:Cram again**^|truc|tu|re:Make into a different form**ar|^|ting|ly:Attracting attention**^|taur|an|ts:Reservation takers**ma|tu|^:Comes to fruition**al|lu|^:Attractive traits',
            'or~^|lan|do:Florida theme-park haven**ema|nc|ip|at|^:Abraham Lincoln, for one**scu|lpt|^:A chipper artist**ig|^:Dr. Frankenstein\'s assistant**dis|^|ie|nts:Befuddles**win|ds|^:Royal surname**^|iole:Black and orange flyer**unc|^|ked:Breathing, especially if an old red**unm|em|^|able:Easily forgotten'
			],
	},
	{
		title:'Last Thirty Days',
		index: '18',
		type:'daily',
		show:'true',
		num_puzzles:'30',
		num_solved:'0',
		solved:'false',
		bg_color:'#FFB300',
		puzzles:[
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something'
			],
	},
	{
		title:'Eggplant',
		index: '19',
		type:'mypack',
		show:'true',
		num_puzzles:'50',
		num_solved:'0',
		solved:'false',
		bg_color:'#2B0B30',
		puzzles:[
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something',
			 'inc~co|nv|^|ed:Certain of something, or made so**^|re|ase:To make greater or add to**un|pr|^|ip|led:Crooked, immoral, or otherwise without scruples**prov|^|ial|ly:In an unsophisticated or narrow-minded manner**co|^|ide|nce:A remarkable concurrence of events**^|apa|ble:Unable to do or achieve (something)**^|ong|ru|ous:Not in harmony or keeping with the surroundings or other aspects of something'
			],
	},
	{
		title:'Strawberry',
		index: '20',
		type:'forsale',
		show:'true',
		num_puzzles:'0',
		num_solved:'0',
		solved:'false',
		bg_color:'#FF43A4',
		puzzles:[
			''
			],
	},
	{
		title:'Banana',
		index: '21',
		type:'forsale',
		show:'true',
		num_puzzles:'0',
		num_solved:'0',
		solved:'false',
		bg_color:'#FFE135',
		puzzles:[
			''
			],
	},
];